version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - .:/var/www/html
      - /var/www/html/node_modules 
    ports:
      - "8080:80" 
    networks:
      - laravel_network
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: laravel_db
    environment:
      MYSQL_DATABASE: laravel_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    networks:
      - laravel_network
    volumes:
      - dbdata:/var/lib/mysql

  vite:
    image: node:20
    container_name: vite_dev_server
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html 
    command: /bin/sh -c "npm install && npm install @rollup/rollup-linux-x64-gnu && npm run dev"
    ports:
      - "5173:5173" 
    networks:
      - laravel_network
    depends_on:
      - app

networks:
  laravel_network:

volumes:
  dbdata:
